esphome:
  name: esp-test
  friendly_name: esp-test

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KhVAtSJaCPLrkX+EP5W8d3e0hvIlOVlAZX+WkIIpSbQ="

ota:
  password: "8e41ab64da3b60d3adf7aa6ab1075d18"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  manual_ip:
    static_ip: 192.168.1.59
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Test Fallback Hotspot"
    password: "DxNT9bVbUfRb"

captive_portal:

# Example configuration entry
i2c:
  sda: D1
  scl: D2

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20

sensor:
  - platform: homeassistant
    id: bkk
    entity_id: sensor.bkk7u
    internal: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(roboto_20), TextAlign::TOP_LEFT , "%f", id(bkk).raw_state);
