########################################
# BASIC STUFF
substitutions:
  name: esphome-web-160662
  friendly_name: ESPHome Web 160662
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
# Enable logging
logger:
# Enable Home Assistant API
api:
  encryption:
    key: "+bCGzU9lsFrxEerCVVyQksM/pMNxNZ9PWsA7QPZozsk="
# Allow Over-The-Air updates
ota:
# Allow provisioning Wi-Fi via serial
improv_serial:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:
# To have a "next url" for improv serial
web_server:


########################################
# MICROCONTROLLER SETUP
esp8266:
  board: d1_mini
i2c:
  sda: D1
  scl: D2
#Display 
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    id: lcd_display 
    lambda: |-      
      // Map weather states to MDI characters (with some extra).
      std::map<std::string, std::string> weather_icon_map
        {
          {"cloudy", "\U000F0590"},
          {"cloudy-alert", "\U000F0F2F"},
          {"cloudy-arrow-right", "\U000F0E6E"},
          {"fog", "\U000F0591"},
          {"hail", "\U000F0592"},
          {"hazy", "\U000F0F30"},
          {"hurricane", "\U000F0898"},
          {"lightning", "\U000F0593"},
          {"lightning-rainy", "\U000F067E"},
          {"night", "\U000F0594"},
          {"night-partly-cloudy", "\U000F0F31"},
          {"partlycloudy", "\U000F0595"},
          {"partly-lightning", "\U000F0F32"},
          {"partly-rainy", "\U000F0F33"},
          {"partly-snowy", "\U000F0F34"},
          {"partly-snowy-rainy", "\U000F0F35"},
          {"pouring", "\U000F0596"},
          {"rainy", "\U000F0597"},
          {"snowy", "\U000F0598"},
          {"snowy-heavy", "\U000F0F36"},
          {"snowy-rainy", "\U000F067F"},
          {"sunny", "\U000F0599"},
          {"sunny-alert", "\U000F0F37"},
          {"sunny-off", "\U000F14E4"},
          {"sunset", "\U000F059A"},
          {"sunset-down", "\U000F059B"},
          {"sunset-up", "\U000F059C"},
          {"tornado", "\U000F0F38"},
          {"windy", "\U000F059D"},
          {"windy-variant", "\U000F059E"},
          {"alarm", "\U000F0020"},
        };

      it.printf(64, 0, id(roboto_10), TextAlign::TOP_CENTER, "Buszok indulnak");
      it.printf(64, 23, id(roboto_20), TextAlign::CENTER, "%s", id(next_buses).state.c_str());
      it.printf(64, 40, id(roboto_10), TextAlign::CENTER, "perc múlva");
      it.strftime(13, 62, id(roboto_10), TextAlign::BASELINE_LEFT, "%H:%M:%S", id(homeassistant_time).now());
      it.printf(0, 64, id(font_mdi_medium), TextAlign::BASELINE_LEFT, weather_icon_map["alarm"].c_str());
      it.printf(116, 62, id(roboto_10), TextAlign::BASELINE_RIGHT, "%sºC", id(weather_temperature_0).state.c_str());
      it.printf(128, 64, id(font_mdi_medium), TextAlign::BASELINE_RIGHT, weather_icon_map[id(weather_condition_0).state.c_str()].c_str());

########################################
# FONTS AND IMAGES
font:
  - file: "gfonts://Chakra%20Petch"
    id: roboto_20
    size: 20
  - file: "gfonts://Chakra%20Petch"
    id: roboto_10
    size: 12
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³áéíóöőúüűÁÉÍÓÖŐÚÜŰº'

  # Include Material Design Icons font
  # Thanks to https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/16
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_large
    size: 16
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
      - "\U000F0020" # mdi-alarm
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_medium
    size: 12
    glyphs: *mdi-weather-glyphs



########################################
# SENSORS AND WHATNOT
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:  
  - platform: wifi_signal
    name: "Weatherman - WiFi Signal Strength"
    id: wifisignal
    unit_of_measurement: "dBm"
    entity_category: "diagnostic"
    update_interval: 60s

  - platform: homeassistant
    entity_id: sensor.bkk_mandula
    id: bkk

text_sensor:
  - platform: homeassistant
    entity_id: sensor.bkk_mandula
    attribute: stationName
    id: mandula_station_name

  - platform: homeassistant
    entity_id: sensor.mandula_bus_0_in
    id: bus_0_in
  - platform: homeassistant
    entity_id: sensor.mandula_bus_1_in
    id: bus_1_in
  - platform: homeassistant
    entity_id: sensor.mandula_bus_2_in
    id: bus_2_in
  - platform: homeassistant
    entity_id: sensor.mandula_bus_3_in
    id: bus_3_in
  - platform: homeassistant
    entity_id: sensor.mandula_bus_4_in
    id: bus_4_in
  - platform: homeassistant
    entity_id: sensor.mandula_next_buses
    id: next_buses

  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_temperature_0
    id: weather_temperature_0
  - platform: homeassistant
    entity_id: sensor.weatherman_data
    attribute: weather_condition_0
    id: weather_condition_0

