- platform: gtfs_rt
  trip_update_url: 'https://go.bkk.hu/api/query/v1/ws/gtfs-rt/full/TripUpdates.pb?key=52a26ae3-3257-4e15-87ad-e46337932b7c'
  vehicle_position_url: 'https://go.bkk.hu/api/query/v1/ws/gtfs-rt/full/VehiclePositions.pb?key=52a26ae3-3257-4e15-87ad-e46337932b7c'
  x_api_key: "52a26ae3-3257-4e15-87ad-e46337932b7c"
  entity_namespace: bkk
  scan_interval: 30
  departures:
    - name: "Gardonyi villamos"
      route: "BKK_0070"
      stopid: "BKK_F02148" 


- platform: bkk_stop
  name: 'bkk7u'
  stopId: 'BKK_F02148'
  minsAfter: 25
  # wheelchair: true
  apiKey: "52a26ae3-3257-4e15-87ad-e46337932b7c"
  routes:
    - 7
    - 114
    - 213
