- platform: bkk_stop
  name: 'bkk_gardonyi'
  stopId: 'BKK_F02148'
  minsAfter: 25
  # wheelchair: true
  apiKey: "52a26ae3-3257-4e15-87ad-e46337932b7c"
  routes:
    - 7
    - 19
    - 41
    - 47
    - 49
    - 56
