########################################
# BASIC STUFF
substitutions:
  name: "tempsensor"
  friendly_name: Temperature Sensor
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
# Enable logging
logger:
# Enable Home Assistant API
api:
  encryption:
    key: "+bCGzU9lsFrxEerCVVyQksM/pMNxNZ9PWsA7QPZozsk="
# Allow Over-The-Air updates
ota:
  platform: esphome
#  password: "your_ota_password_here"
# Allow provisioning Wi-Fi via serial
improv_serial:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:
# To have a "next url" for improv serial
web_server:


########################################
# MICROCONTROLLER SETUP
esp8266:
  board: d1_mini
i2c:
  sda: D1
  scl: D2
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    id: lcd_display 
    lambda: |-      
      it.printf(64, 0, id(font_big), TextAlign::TOP_CENTER, "%.1f ºC", id(balc_temp).state);
      it.printf(64, 60, id(font_small), TextAlign::BASELINE_CENTER, "Humidity: %.1f%%", id(balc_hum).state);


########################################
# FONTS AND IMAGES
font:
  - file: "gfonts://Chakra%20Petch"
    id: font_small
    size: 14
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³áéíóöőúüűÁÉÍÓÖŐÚÜŰº'
  - file: "gfonts://Chakra%20Petch"
    id: font_big
    size: 36
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³áéíóöőúüűÁÉÍÓÖŐÚÜŰº'

########################################
# SENSORS AND WHATNOT
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:  
  - platform: wifi_signal
    name: "Balcony - WiFi Signal Strength"
    id: wifisignal
    unit_of_measurement: "dBm"
    entity_category: "diagnostic"
    update_interval: 60s

  - platform: dht
    pin: D5
    temperature:
      id: balc_temp
      name: "Balcony Temperature"
    humidity:
      id: balc_hum
      name: "Balcony Humidity"
    update_interval: 60s
    model: DHT22



